In [1]:
import numpy as np

In [2]:
x = np.array(12)
x.ndim

0

In [4]:
a = np.array([1,2,3])
a.ndim

1

In [6]:
b = np.array([[1,2,3]])
b.ndim

2

In [9]:
c = np.array([[[1,2,3]]])
c.ndim

(1, 1, 3)

In [10]:
print('shape of a: ', a.shape)
print('shape of b: ', b.shape)
print('shape of c: ', c.shape)

# 1D Tensor = (?,)
# 2D Tensor = (?,?)
# 3D Tensor = (?,?,?)
# Rank = ndim 즉 차원 갯수

shape of a:  (3,)
shape of b:  (1, 3)
shape of c:  (1, 1, 3)


In [ ]:
# Scalar - 0D Tensor
# Vector = 1D Tensor
# Matrix - 2D Tensor
# 행렬 괄호 3개 - 3D Tensor
# 행렬 괄호 4개 - 4D Tensor

In [20]:
# Element-wise operations
def naive_relu(x):
  assert len(x.shape) == 2

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j],0)
  return x

def naive_add(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]
  return x

In [28]:
# Numpy 행렬을 사용할 때, naive_relu 라던지, naive_add 기능은 이미 Built_in 되어 있음.
# 그래서 Numpy 이용이 엄청 간편한 것.
import numpy as np

x = np.array([[1,2,3],[2,5,1]])
y = np.array([[10,10,10],[20,20,20]])
z = x+y
print(z)

np.max(z, 0)

[[11 12 13]
 [22 25 21]]


array([22, 25, 21])

In [29]:
# Broadcasting - 모든 행렬에 전파하여 합해지는 기능
def naive_add_matrix_vector(x,y):
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1] == y.shape[0]

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[j]
  return x

In [31]:
import numpy as np

x = np.random.random((64,3,32,10))
y = np.random.random((32,10))

z = np.maximum(x,y)

# Broadcasting 기능.

In [38]:
# Tensor dot
def naive_vector_dot(x,y):
  assert len(x.shape)==1
  assert len(y.shape)==1
  assert x.shape[0]==y.shape[0]

  z = 0.
  for i in range(x.shape[0]):
    z += x[i]*y[i]
  return z

In [41]:
import numpy as np
def naive_matrix_vector_dot(x,y):
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1]==y.shape[0]
  
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] += x[i,j] + y[j]
  return z

def naive_matrix_vector_dot(x,y):
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1]==y.shape[0]
  
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    z = naive_vector_dot(x[i,:],y)
  return z

In [45]:
def naive_matrix_dot(x,y):
  assert len(x.shape)==2
  assert len(y.shape)==2
  assert x.shape[1] == y.shape[0]

  z = np.zeros((x.shape[0], y.shape[1]))
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i,:]
      column_y = y[:,j]
      z[i,j] = naive_vector_dot(row_x, column_y)
  return z

In [46]:
# Tensor Reshaping
# Tensor Reshaping : 행과 열들을 target shape에 맞게 다시 재조정하는 것을 의미한다.

x = np.array([[0., 1.,], [2., 3.], [4., 5.]])
print(x.shape)

(3, 2)


In [47]:
x.reshape(6,1) # or (-1,1)

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [48]:
x.reshape(2,3)

array([[0., 1., 2.],
       [3., 4., 5.]])

In [49]:
np.transpose(x)

array([[0., 2., 4.],
       [1., 3., 5.]])